### PR TITLE
Added temporary solution to the concurrency problem

### LINKED ISSUE #37: Concurrency Problem
Currently there is a concurrency problem, which is described in the following document:

https://docs.google.com/document/d/1CtNeKLeLlyE_fk1e3bDktJ63oIQ5MDANLdriXfrFCvU/edit

### PR DESCRIPTION
**Pull request by iPablo**
Fix #37

### CODE REVIEW

**Comment by iPablo** [comment]
Done

**Comment by alfem** [comment]
Thanks!

This configuration template (for the automated installation procedure) is also affected by your changes:

 https://github.com/gecos-team/cookbook-gecosccui/blob/master/templates/default/gecoscc.ini.erb 

Please, include this brand new parameter in the template and add this file to your pull request.

**Comment by iPablo** [comment]
Correct me if I'm wrong, I think is done in PR[1] but I forgot to mention it in this PR.

1 - https://github.com/gecos-team/cookbook-gecosccui/pull/1

**Comment by alfem** [comment]
You are absolutely right!

"Too many repositories" syndrom :-)

**Pull request merged**
